import type { ReportLanguage } from '../types/analysis';

export const normalizeReportLanguage = (value?: string | null): ReportLanguage =>
  value === 'en' ? 'en' : 'zh';

const REPORT_TEXT = {
  zh: {
    keyInsights: '核心洞察',
    noAnalysisSummary: '暂无分析结论',
    actionAdvice: '操作建议',
    noAdvice: '暂无建议',
    trendPrediction: '趋势预测',
    noPrediction: '暂无预测',
    marketSentiment: '市场情绪',
    strategyPoints: '策略点位',
    sniperLevels: '狙击点位',
    idealBuy: '理想买入',
    secondaryBuy: '二次买入',
    stopLoss: '止损价位',
    takeProfit: '止盈目标',
    noValue: '—',
    newsFeed: '资讯动态',
    relatedNews: '相关资讯',
    refresh: '刷新',
    retry: '重试',
    dismiss: '关闭',
    details: '查看详情',
    loadingNews: '加载资讯中...',
    noNews: '暂无相关资讯',
    noNewsDescription: '可稍后刷新以获取最新资讯。',
    openLink: '跳转',
    transparency: '透明度',
    traceability: '数据追溯',
    rawResult: '原始分析结果',
    analysisSnapshot: '分析快照',
    copy: '复制',
    copied: '已复制',
    recordId: '记录 ID',
    fullReport: '完整分析报告',
    loadingReport: '加载报告中...',
    loadReportFailed: '加载报告失败',
    copyMarkdownSource: '复制 Markdown 源码',
    copyPlainText: '复制纯文本',
    analysisModel: '分析模型',
    fearGreedIndex: '恐惧贪婪指数',
    boardLinkage: '板块联动',
    relatedBoards: '关联板块',
    leadingBoard: '领涨',
    laggingBoard: '领跌',
    neutralBoard: '中性',
    basicInfo: '基础信息',
    stockName: '股票名称',
    stockCode: '股票代码',
    reportType: '报告类型',
    reportLanguage: '报告语言',
    queryId: '查询 ID',
    recordIdLabel: '记录 ID',
    area: '地域',
    industry: '行业',
    market: '市场板块',
    listDate: '上市日期',
    symbol: '证券代码',
    tsCode: 'TS 代码',
    cnspell: '拼音缩写',
    actName: '实控人名称',
    actEntType: '实控人企业性质',
    companyProfile: '公司介绍',
    companyName: '公司名称',
    companyIntro: '公司简介',
    mainBusiness: '主营业务',
    businessScope: '业务范围',
    financialMetrics: '财务指标',
    asOf: '口径时间',
    peRatio: '市盈率(PE)',
    pbRatio: '市净率(PB)',
    psRatio: '市销率(PS)',
    pegRatio: 'PEG',
    dividendYield: '股息率',
    totalMarketValue: '总市值',
    floatMarketValue: '流通市值',
    roe: 'ROE',
    roa: 'ROA',
    grossMargin: '毛利率',
    netMargin: '净利率',
    debtRatio: '资产负债率',
    revenue: '营收',
    netProfitParent: '归母净利润',
    operatingCashFlow: '经营现金流',
    revenueYoy: '营收同比',
    netProfitYoy: '净利润同比',
    loadingCompanyInsights: '加载公司信息与财务指标中...',
    companyInsightsUnavailable: '暂无公司信息与财务指标数据',
  },
  en: {
    keyInsights: 'KEY INSIGHTS',
    noAnalysisSummary: 'No analysis summary yet',
    actionAdvice: 'Action Advice',
    noAdvice: 'No advice yet',
    trendPrediction: 'Trend Outlook',
    noPrediction: 'No forecast yet',
    marketSentiment: 'Market Sentiment',
    strategyPoints: 'STRATEGY POINTS',
    sniperLevels: 'Action Levels',
    idealBuy: 'Ideal Entry',
    secondaryBuy: 'Secondary Entry',
    stopLoss: 'Stop Loss',
    takeProfit: 'Take Profit',
    noValue: '—',
    newsFeed: 'NEWS FEED',
    relatedNews: 'Related News',
    refresh: 'Refresh',
    retry: 'Retry',
    dismiss: 'Close',
    details: 'View details',
    loadingNews: 'Loading news...',
    noNews: 'No related news',
    noNewsDescription: 'Refresh later to check for the latest updates.',
    openLink: 'Open',
    transparency: 'TRANSPARENCY',
    traceability: 'Data Traceability',
    rawResult: 'Raw Analysis Result',
    analysisSnapshot: 'Analysis Snapshot',
    copy: 'Copy',
    copied: 'Copied!',
    recordId: 'Record ID',
    fullReport: 'Full Analysis Report',
    loadingReport: 'Loading report...',
    loadReportFailed: 'Failed to load report',
    copyMarkdownSource: 'Copy Markdown Source',
    copyPlainText: 'Copy Plain Text',
    analysisModel: 'Model',
    fearGreedIndex: 'Fear & Greed Index',
    boardLinkage: 'BOARD LINKAGE',
    relatedBoards: 'Related Boards',
    leadingBoard: 'Leading',
    laggingBoard: 'Lagging',
    neutralBoard: 'Neutral',
    basicInfo: 'Basic Info',
    stockName: 'Name',
    stockCode: 'Code',
    reportType: 'Report Type',
    reportLanguage: 'Language',
    queryId: 'Query ID',
    recordIdLabel: 'Record ID',
    area: 'Region',
    industry: 'Industry',
    market: 'Market',
    listDate: 'List Date',
    symbol: 'Symbol',
    tsCode: 'TS Code',
    cnspell: 'Pinyin',
    actName: 'Controller',
    actEntType: 'Controller Type',
    companyProfile: 'Company Profile',
    companyName: 'Company Name',
    companyIntro: 'Company Intro',
    mainBusiness: 'Main Business',
    businessScope: 'Business Scope',
    financialMetrics: 'Financial Metrics',
    asOf: 'As Of',
    peRatio: 'PE Ratio',
    pbRatio: 'PB Ratio',
    psRatio: 'PS Ratio',
    pegRatio: 'PEG Ratio',
    dividendYield: 'Dividend Yield',
    totalMarketValue: 'Total Market Value',
    floatMarketValue: 'Float Market Value',
    roe: 'ROE',
    roa: 'ROA',
    grossMargin: 'Gross Margin',
    netMargin: 'Net Margin',
    debtRatio: 'Debt Ratio',
    revenue: 'Revenue',
    netProfitParent: 'Net Profit (Parent)',
    operatingCashFlow: 'Operating Cash Flow',
    revenueYoy: 'Revenue YoY',
    netProfitYoy: 'Net Profit YoY',
    loadingCompanyInsights: 'Loading company profile and financial metrics...',
    companyInsightsUnavailable: 'Company profile and financial metrics are unavailable',
  },
} as const;

export const getReportText = (language?: string | null) => REPORT_TEXT[normalizeReportLanguage(language)];
